apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-disk
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "" 
  resources:
    requests:
      storage: 8Gi
  volumeName: pv-disk
