apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-file
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-file
