apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-1
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "" 
  resources:
    requests:
      storage: 8Gi
  volumeName: test-pv-1