apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-disk-1
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "" 
  resources:
    requests:
      storage: 8Gi
  volumeName: test-pv-disk-1
