apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv-disk-1
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes: [ "ReadWriteOnce" ]
  azureDisk: 
    kind: Managed
    diskName: test-pv-disk
    diskURI: <생성한 Disk URI 주소>
