apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-disk
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes: [ "ReadWriteOnce" ]
  azureDisk: 
    kind: Managed
    diskName: auzre-disk
    diskURI: <생성한 Disk URI 주소>
