apiVersion: acme.cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - hello-world-ingress.MY_CUSTOM_DNS
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - hello-world-ingress.MY_CUSTOM_DNS
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
