apiVersion: acme.cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - hw-ingress.jye.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - hw-ingress.jye.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer