apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jye112@naver.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        azuredns:
          clientID: 
          clientSecretSecretRef:
            name: azuredns-config
            key: client-secret
          subscriptionID: 
          tenantID: 
          resourceGroupName: aks-cluster-rg
          hostedZoneName: jye.com
          environment: AzurePublicCloud


          

#    - http01:
#        ingress:
#          class: nginx
#          podTemplate:
#            spec:
#              nodeSelector:
#                "kubernetes.io/os": linux