apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: dkagh1.
        - name: MYSQL_DATABASE
          value: wordpress_db
        - name: MYSQL_USER
          value: wp-admin
        - name: MYSQL_ROOT_HOST
          value: '%'  
        - name: MYSQL_PASSWORD 
          value: dkagh1.
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          requests: # 최소
            cpu: 250m
            memory: 128Mi
          limits:   # 최대
            cpu: 500m
            memory: 1280Mi  # mysql pod 하나가 450Mi 이상의 메모리 사용
#        livenessProbe:
#          exec:
#            command: ["mysqladmin", "ping"]
#          initialDelaySeconds: 30
#          periodSeconds: 10
#          timeoutSeconds: 5
#        readinessProbe:
#          exec:
#            command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
#          initialDelaySeconds: 5
#          periodSeconds: 2
#          timeoutSeconds: 1         
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-pvc
  volumeClaimTemplates:
  - metadata:
      name: mysql-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "default"  # kubectl get storageclass로 종류 확인
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
