apiVersion: v1
kind: PersistentVolume
metadata:
  name: test1-pv-1
spec:
  capacity:
    storage: 2Gi
  storageClassName: azurefile  # azurefile의 경우 storageClassName을 명시하지 않으면 default(azureDisk)로 생성되므로 밑에 azureFile 구성 파라미터들과 충돌
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    secretNamespace: default
    shareName: aksshare
    readOnly: false
  mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test1-pvc-1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 2Gi
  volumeName: test1-pv-1
